district_to_exercises:
    'petto':
        - 'croci al cavo basso'
        - 'croci al cavo alto'
        - 'croci ai cavi'
        - 'croci con manubri'
        - 'panca piana con bilanciere'
        - 'panca inclinata con bilanciere 45'
        - 'panca inclinata con bilanciere 30'
        - 'panca declinata'
        - 'panca piana con manubri'
        - 'panca inclinata 45 con manubri'
        - 'panca inclinata 30 con manubri'
        - 'panca declinata con manubri'
        - 'pectoral machine'
        - 'panca piana multipower'
        - 'panca inclinata multipower 45'
        - 'panca inclinata multipower 30'
        - 'panca declinata multipower'
        - 'dip alle parallele'
        - 'push up'
    'spalle':
        - 'military press con bilanciere'
        - 'spinte in alto con manubri seduto'
        - 'spinte in alto con manubri in piedi'
        - 'alzate laterali singola'
        - 'alzate laterali in piedi'
        - 'alzate laterali da seduto'
        - 'alzate laterali su panca inclinata'
        - 'alzate laterali ai cavi'
        - 'alzate frontali in piedi'
        - 'alzate frontali da seduto'
        - 'alzate frontali ai cavi'
        - 'tirate al mento con bilanciere'
        - 'tirate al petto con bilanciere'
        - 'tirate al petto con manubri'
        - 'tirate al mento con manubri'
        - 'aperture con manubri su panca'
        - 'aperture ai cavi'
        - 'rear delt machine'
        - 'face pull'
        - 'shrug manubri'
    'dorsali':
      - 'lat machine triangolo'
      - 'lat machine presa larga'
      - 'lat machine presa inversa'
      - 'lat machine'
      - 'trazioni'
      - 'trazioni presa inversa'
      - 'rematore con bilanciere'
      - 'rematore t-bar'
      - 'rematore con manubrio su panca'
      - 'pulley triangolo'
      - 'pulley presa larga'
      - 'rowing machine'
      - 'pull down'
      - 'stacco da terra (dorsali)'
      - 'hyperextension (lombari)'
    'bicipiti':
        - 'curl con manubri in piedi'
        - 'curl con manubri seduto'
        - 'curl con bilanciere ez in piedi'
        - 'curl con bilanciere ez seduto'
        - 'curl con manubri panca 60'
        - 'curl con manubri panca 45'
        - 'preacher curl con bilanciere'
        - 'preacher curl con manubri'
        - 'preacher curl a un braccio'
        - 'curl ai cavi'
    'tricipiti':
        - 'panca piana presa stretta'
        - 'panca piana manubri presa stretta'
        - 'french press con bilanciere'
        - 'french press con manubri'
        - 'french press al cavo alto'
        - 'french press al cavo basso'
        - 'push down corda'
        - 'push down triangolo'
        - 'kick back manubrio'
        - 'kick back cavo'
        - 'push up stretti'
        - 'dips tra panche'
    'gambe':
        - 'squat'
        - 'squat multipower'
        - 'sumo squat'
        - 'hack squat'
        - 'squat bulgaro'
        - 'leg press verticale'
        - 'leg press orizzontale'
        - 'leg press 45'
        - 'leg press focus quads'
        - 'stacco da terra (gambe)'
        - 'stacco da terra sumo'
        - 'stacco con trap bar'
        - 'stacco a gambe semi-tese'
        - 'stacco rumeno'
        - 'hyperextension (gambe)'
        - 'affondi indietro'
        - 'affondi in camminata'
        - 'affondi statici manubri'
        - 'affondi statici bilanciere'
        - 'affondi multipower'
        - 'step up'
        - 'hip thrust bilanciere'
        - 'hip thrust machine'
        - 'ponte con sovraccarico'
        - 'leg curl'
        - 'leg curl seduto'
        - 'leg curl in piedi'
        - 'leg extension'
        - 'slanci al cavo'
        - 'adductor machine'
        - 'abductor machine'
        - 'calf machine seduto'
        - 'calf machine in piedi'
        - 'calf al multipower in piedi'
        - 'abduzioni in piedi ai cavi'
        - 'adduzioni in piedi ai cavi'

exercise_to_district:
    'croci al cavo basso': 'petto'
    'croci al cavo alto': 'petto'
    'croci ai cavi': 'petto'
    'croci con manubri': 'petto'
    'panca piana con bilanciere': 'petto'
    'panca inclinata con bilanciere 45': 'petto'
    'panca inclinata con bilanciere 30': 'petto'
    'panca declinata': 'petto'
    'panca piana con manubri': 'petto'
    'panca inclinata 45 con manubri': 'petto'
    'panca inclinata 30 con manubri': 'petto'
    'panca declinata con manubri': 'petto'
    'pectoral machine': 'petto'
    'panca piana multipower': 'petto'
    'panca inclinata multipower 45': 'petto'
    'panca inclinata multipower 30': 'petto'
    'panca declinata multipower': 'petto'
    'dip alle parallele': 'petto'
    'push up': 'petto'
    'military press con bilanciere': 'spalle'
    'spinte in alto con manubri seduto': 'spalle'
    'spinte in alto con manubri in piedi': 'spalle'
    'alzate laterali singola': 'spalle'
    'alzate laterali in piedi': 'spalle'
    'alzate laterali da seduto': 'spalle'
    'alzate laterali su panca inclinata': 'spalle'
    'alzate laterali ai cavi': 'spalle'
    'alzate frontali in piedi': 'spalle'
    'alzate frontali da seduto': 'spalle'
    'alzate frontali ai cavi': 'spalle'
    'tirate al mento con bilanciere': 'spalle'
    'tirate al petto con bilanciere': 'spalle'
    'tirate al petto con manubri': 'spalle'
    'tirate al mento con manubri': 'spalle'
    'aperture con manubri su panca': 'spalle'
    'aperture ai cavi': 'spalle'
    'rear delt machine': 'spalle'
    'face pull': 'spalle'
    'shrug manubri': 'spalle'
    'lat machine triangolo': 'dorsali'
    'lat machine presa larga': 'dorsali'
    'lat machine presa inversa': 'dorsali'
    'lat machine': 'dorsali'
    'trazioni': 'dorsali'
    'trazioni presa inversa': 'dorsali'
    'rematore con bilanciere': 'dorsali'
    'rematore t-bar': 'dorsali'
    'rematore con manubrio su panca': 'dorsali'
    'pulley triangolo': 'dorsali'
    'pulley presa larga': 'dorsali'
    'rowing machine': 'dorsali'
    'pull down': 'dorsali'
    'stacco da terra (dorsali)': 'dorsali'
    'hyperextension (lombari)': 'dorsali'
    'curl con manubri in piedi': 'bicipiti'
    'curl con manubri seduto': 'bicipiti'
    'curl con bilanciere ez in piedi': 'bicipiti'
    'curl con bilanciere ez seduto': 'bicipiti'
    'curl con manubri panca 60': 'bicipiti'
    'curl con manubri panca 45': 'bicipiti'
    'preacher curl con bilanciere': 'bicipiti'
    'preacher curl con manubri': 'bicipiti'
    'preacher curl a un braccio': 'bicipiti'
    'curl ai cavi': 'bicipiti'
    'panca piana presa stretta': 'tricipiti'
    'panca piana manubri presa stretta': 'tricipiti'
    'french press con bilanciere': 'tricipiti'
    'french press con manubri': 'tricipiti'
    'french press al cavo alto': 'tricipiti'
    'french press al cavo basso': 'tricipiti'
    'push down corda': 'tricipiti'
    'push down triangolo': 'tricipiti'
    'kick back manubrio': 'tricipiti'
    'kick back cavo': 'tricipiti'
    'push up stretti': 'tricipiti'
    'dips tra panche': 'tricipiti'
    'squat': 'gambe'
    'squat multipower': 'gambe'
    'sumo squat': 'gambe'
    'hack squat': 'gambe'
    'squat bulgaro': 'gambe'
    'leg press verticale': 'gambe'
    'leg press orizzontale': 'gambe'
    'leg press 45': 'gambe'
    'leg press focus quads': 'gambe'
    'stacco da terra (gambe)': 'gambe'
    'stacco da terra sumo': 'gambe'
    'stacco con trap bar': 'gambe'
    'stacco a gambe semi-tese': 'gambe'
    'stacco rumeno': 'gambe'
    'hyperextension (gluteo)': 'gambe'
    'affondi indietro': 'gambe'
    'affondi in camminata': 'gambe'
    'affondi statici manubri': 'gambe'
    'affondi statici bilanciere': 'gambe'
    'affondi multipower': 'gambe'
    'step up': 'gambe'
    'hip thrust bilanciere': 'gambe'
    'hip thrust machine': 'gambe'
    'ponte con sovraccarico': 'gambe'
    'leg curl': 'gambe'
    'leg curl seduto': 'gambe'
    'leg curl in piedi': 'gambe'
    'leg extension': 'gambe'
    'slanci al cavo': 'gambe'
    'adductor machine': 'gambe'
    'abductor machine': 'gambe'
    'calf machine seduto': 'gambe'
    'calf machine in piedi': 'gambe'
    'calf al multipower in piedi': 'gambe'
    'abduzioni in piedi ai cavi': 'gambe'
    'adduzioni in piedi ai cavi': 'gambe'
