district_to_exercises:
    'chest':
        - 'low cable fly'
        - 'high cable fly'
        - 'cable fly'
        - 'dumbbell fly'
        - 'flat bench press with barbell'
        - 'incline bench press with barbell 45'
        - 'incline bench press with barbell 30'
        - 'decline bench press'
        - 'flat bench press with dumbbells'
        - 'incline bench press 45 with dumbbells'
        - 'incline bench press 30 with dumbbells'
        - 'decline bench press with dumbbells'
        - 'pectoral machine'
        - 'flat bench press with smith machine'
        - 'incline bench press 45 with smith machine'
        - 'incline bench press 30 with smith machine'
        - 'decline bench press with smith machine'
        - 'parallel bar dips'
        - 'push up'
    'shoulders':
        - 'military press with barbell'
        - 'seated dumbbell shoulder press'
        - 'standing dumbbell shoulder press'
        - 'single lateral raise'
        - 'standing lateral raise'
        - 'seated lateral raise'
        - 'incline bench lateral raise'
        - 'cable lateral raise'
        - 'standing front raise'
        - 'seated front raise'
        - 'cable front raise'
        - 'barbell upright row'
        - 'barbell high pull'
        - 'dumbbell high pull'
        - 'dumbbell upright row'
        - 'incline bench dumbbell fly'
        - 'cable fly'
        - 'rear delt machine'
        - 'face pull'
        - 'dumbbell shrug'
    'back':
      - 'lat pulldown with close grip'
      - 'lat pulldown with wide grip'
      - 'lat pulldown with reverse grip'
      - 'lat pulldown'
      - 'pull-ups'
      - 'chin-ups'
      - 'barbell row'
      - 't-bar row'
      - 'dumbbell row on bench'
      - 'seated cable row with close grip'
      - 'seated cable row with wide grip'
      - 'rowing machine'
      - 'pull-down'
      - 'deadlift (back)'
      - 'hyperextension (lower back)'
    'biceps':
        - 'standing dumbbell curl'
        - 'seated dumbbell curl'
        - 'standing ez barbell curl'
        - 'seated ez barbell curl'
        - 'incline dumbbell curl 60'
        - 'incline dumbbell curl 45'
        - 'preacher curl with barbell'
        - 'preacher curl with dumbbells'
        - 'single-arm preacher curl'
        - 'cable curl'
    'triceps':
        - 'close grip bench press'
        - 'close grip bench press with dumbbells'
        - 'french press with barbell'
        - 'french press with dumbbells'
        - 'french press with high cable'
        - 'french press with low cable'
        - 'rope pushdown'
        - 'triangle pushdown'
        - 'dumbbell kickback'
        - 'cable kickback (triceps)'
        - 'close grip push-up'
        - 'bench dips'
    'legs':
        - 'squat'
        - 'smith machine squat'
        - 'sumo squat'
        - 'hack squat'
        - 'bulgarian split squat'
        - 'vertical leg press'
        - 'horizontal leg press'
        - '45 leg press'
        - 'leg press focus quads'
        - 'deadlift (legs)'
        - 'sumo deadlift'
        - 'trap bar deadlift'
        - 'stiff-legged deadlift'
        - 'romanian deadlift'
        - 'hyperextension (glutes)'
        - 'reverse lunges'
        - 'walking lunges'
        - 'static lunges with dumbbells'
        - 'static lunges with barbell'
        - 'smith machine lunges'
        - 'step-up'
        - 'hip thrust with barbell'
        - 'hip thrust machine'
        - 'weighted bridge'
        - 'leg curl'
        - 'seated leg curl'
        - 'standing leg curl'
        - 'leg extension'
        - 'cable kickback'
        - 'adductor machine'
        - 'abductor machine'
        - 'seated calf raise machine'
        - 'standing calf raise machine'
        - 'smith machine standing calf raise'
        - 'cable standing abductions'
        - 'cable standing adductions'

exercise_to_district:
    'low cable fly': 'chest'
    'high cable fly': 'chest'
    'cable fly': 'chest'
    'dumbbell fly': 'chest'
    'flat bench press with barbell': 'chest'
    'incline bench press with barbell 45': 'chest'
    'incline bench press with barbell 30': 'chest'
    'decline bench press': 'chest'
    'flat bench press with dumbbells': 'chest'
    'incline bench press 45 with dumbbells': 'chest'
    'incline bench press 30 with dumbbells': 'chest'
    'decline bench press with dumbbells': 'chest'
    'pectoral machine': 'chest'
    'flat bench press with smith machine': 'chest'
    'incline bench press 45 with smith machine': 'chest'
    'incline bench press 30 with smith machine': 'chest'
    'decline bench press with smith machine': 'chest'
    'parallel bar dips': 'chest'
    'push up': 'chest'
    'military press with barbell': 'shoulders'
    'seated dumbbell shoulder press': 'shoulders'
    'standing dumbbell shoulder press': 'shoulders'
    'single lateral raise': 'shoulders'
    'standing lateral raise': 'shoulders'
    'seated lateral raise': 'shoulders'
    'incline bench lateral raise': 'shoulders'
    'cable lateral raise': 'shoulders'
    'standing front raise': 'shoulders'
    'seated front raise': 'shoulders'
    'cable front raise': 'shoulders'
    'barbell upright row': 'shoulders'
    'barbell high pull': 'shoulders'
    'dumbbell high pull': 'shoulders'
    'dumbbell upright row': 'shoulders'
    'incline bench dumbbell fly': 'shoulders'
    'cable fly': 'shoulders'
    'rear delt machine': 'shoulders'
    'face pull': 'shoulders'
    'dumbbell shrug': 'shoulders'
    'lat pulldown with close grip': 'back'
    'lat pulldown with wide grip': 'back'
    'lat pulldown with reverse grip': 'back'
    'lat pulldown': 'back'
    'pull-ups': 'back'
    'chin-ups': 'back'
    'barbell row': 'back'
    't-bar row': 'back'
    'dumbbell row on bench': 'back'
    'seated cable row with close grip': 'back'
    'seated cable row with wide grip': 'back'
    'rowing machine': 'back'
    'pull-down': 'back'
    'deadlift (back)': 'back'
    'hyperextension (lower back)': 'back'
    'standing dumbbell curl': 'biceps'
    'seated dumbbell curl': 'biceps'
    'standing ez barbell curl': 'biceps'
    'seated ez barbell curl': 'biceps'
    'incline dumbbell curl 60': 'biceps'
    'incline dumbbell curl 45': 'biceps'
    'preacher curl with barbell': 'biceps'
    'preacher curl with dumbbells': 'biceps'
    'single-arm preacher curl': 'biceps'
    'cable curl': 'biceps'
    'close grip bench press': 'triceps'
    'close grip bench press with dumbbells': 'triceps'
    'french press with barbell': 'triceps'
    'french press with dumbbells': 'triceps'
    'french press with high cable': 'triceps'
    'french press with low cable': 'triceps'
    'rope pushdown': 'triceps'
    'triangle pushdown': 'triceps'
    'dumbbell kickback': 'triceps'
    'cable kickback (triceps)': 'triceps'
    'close grip push-up': 'triceps'
    'bench dips': 'triceps'
    'squat': 'legs'
    'smith machine squat': 'legs'
    'sumo squat': 'legs'
    'hack squat': 'legs'
    'bulgarian split squat': 'legs'
    'vertical leg press': 'legs'
    'horizontal leg press': 'legs'
    '45 leg press': 'legs'
    'leg press focus quads': 'legs'
    'deadlift (legs)': 'legs'
    'sumo deadlift': 'legs'
    'trap bar deadlift': 'legs'
    'stiff-legged deadlift': 'legs'
    'romanian deadlift': 'legs'
    'hyperextension (glutes)': 'legs'
    'reverse lunges': 'legs'
    'walking lunges': 'legs'
    'static lunges with dumbbells': 'legs'
    'static lunges with barbell': 'legs'
    'smith machine lunges': 'legs'
    'step-up': 'legs'
    'hip thrust with barbell': 'legs'
    'hip thrust machine': 'legs'
    'weighted bridge': 'legs'
    'leg curl': 'legs'
    'seated leg curl': 'legs'
    'standing leg curl': 'legs'
    'leg extension': 'legs'
    'cable kickback': 'legs'
    'adductor machine': 'legs'
    'abductor machine': 'legs'
    'seated calf raise machine': 'legs'
    'standing calf raise machine': 'legs'
    'smith machine standing calf raise': 'legs'
    'cable standing abductions': 'legs'
    'cable standing adductions': 'legs'
